// Command kms-support provides support operations used only to prepare
// black-box system tests for kms-import. It is intentionally not included in
// GoReleaser, release artifacts, or installation documentation.
package main

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"io"
	"os"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/kms"
	"github.com/aws/aws-sdk-go-v2/service/kms/types"
	clipkg "github.com/urfave/cli/v3"
)

const (
	// rsaKeyBits is the only RSA key size generated by kms-support; it matches
	// the RSA_2048 keys created by kms-create-key and the documented kms-import
	// input format.
	rsaKeyBits = 2048

	// privateKeyFileMode is the filesystem mode for a freshly generated private
	// key. Group and other permissions are removed.
	privateKeyFileMode = 0o600
)

// command returns the kms-support command tree.
func command() *clipkg.Command {
	return &clipkg.Command{
		Name:  "kms-support",
		Usage: "support commands for kms-import system tests",
		Commands: []*clipkg.Command{
			generateKeyCommand(),
			createKeyCommand(),
		},
	}
}

func generateKeyCommand() *clipkg.Command {
	pkcs1Flag := &clipkg.BoolFlag{Name: "pkcs1", Usage: "write a PKCS#1 PEM (\"RSA PRIVATE KEY\")"}
	pkcs8Flag := &clipkg.BoolFlag{Name: "pkcs8", Usage: "write a PKCS#8 PEM (\"PRIVATE KEY\")"}

	return &clipkg.Command{
		Name:      "generate-key",
		Usage:     "generate a fresh RSA-2048 private key PEM",
		UsageText: "kms-support generate-key (--pkcs1 | --pkcs8) --output <path>",
		Flags: []clipkg.Flag{
			pkcs1Flag,
			pkcs8Flag,
			&clipkg.StringFlag{
				Name:     "output",
				Usage:    "secure path where the generated PEM will be written; must not already exist",
				Required: true,
			},
		},
		MutuallyExclusiveFlags: []clipkg.MutuallyExclusiveFlags{
			{
				Required: true,
				Flags:    [][]clipkg.Flag{{pkcs1Flag}, {pkcs8Flag}},
			},
		},
		Action: func(ctx context.Context, cmd *clipkg.Command) error {
			format := "pkcs8"
			if cmd.Bool("pkcs1") {
				format = "pkcs1"
			}
			return generateKey(format, cmd.String("output"))
		},
	}
}

// generateKey creates a new RSA-2048 private key and writes it to outputPath as
// either a PKCS#1 or PKCS#8 PEM. It refuses to overwrite an existing file and
// creates the new file with 0o600 permissions.
func generateKey(format, outputPath string) error {
	var blockType string
	var marshal func(priv *rsa.PrivateKey) ([]byte, error)

	switch format {
	case "pkcs1":
		blockType = "RSA PRIVATE KEY"
		marshal = func(priv *rsa.PrivateKey) ([]byte, error) {
			return x509.MarshalPKCS1PrivateKey(priv), nil
		}
	case "pkcs8":
		blockType = "PRIVATE KEY"
		marshal = func(priv *rsa.PrivateKey) ([]byte, error) {
			return x509.MarshalPKCS8PrivateKey(priv)
		}
	default:
		return fmt.Errorf("unsupported format %q: want pkcs1 or pkcs8", format)
	}

	if _, err := os.Stat(outputPath); err == nil {
		return fmt.Errorf("output file %q already exists", outputPath)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("check output path %q: %w", outputPath, err)
	}

	priv, err := rsa.GenerateKey(rand.Reader, rsaKeyBits)
	if err != nil {
		return fmt.Errorf("generate RSA key: %w", err)
	}

	der, err := marshal(priv)
	if err != nil {
		return fmt.Errorf("marshal private key: %w", err)
	}

	pemBytes := pem.EncodeToMemory(&pem.Block{Type: blockType, Bytes: der})
	if err := os.WriteFile(outputPath, pemBytes, privateKeyFileMode); err != nil {
		return fmt.Errorf("write private key: %w", err)
	}

	return nil
}

// createKeyClient is the subset of the AWS KMS API required by createTargetKey.
type createKeyClient interface {
	CreateKey(ctx context.Context, params *kms.CreateKeyInput, optFns ...func(*kms.Options)) (*kms.CreateKeyOutput, error)
}

func createKeyCommand() *clipkg.Command {
	return &clipkg.Command{
		Name:      "kms-create-key",
		Usage:     "create an EXTERNAL RSA_2048 SIGN_VERIFY KMS key",
		UsageText: "kms-support kms-create-key",
		Description: `Create a KMS key suitable for importing RSA-2048 key material.

The created key has origin EXTERNAL, key spec RSA_2048, and key usage
SIGN_VERIFY. The AWS SDK endpoint, region, and credentials are resolved
from the environment; no flags are accepted. The new key's identifier is
written to stdout; diagnostics are written to stderr.`,
		Action: func(ctx context.Context, cmd *clipkg.Command) error {
			cfg, err := config.LoadDefaultConfig(ctx)
			if err != nil {
				return fmt.Errorf("load AWS config: %w", err)
			}
			return createTargetKey(ctx, kms.NewFromConfig(cfg), cmd.Writer)
		},
	}
}

// createTargetKey creates an EXTERNAL/RSA_2048/SIGN_VERIFY KMS key using client
// and writes the resulting key identifier to w.
func createTargetKey(ctx context.Context, client createKeyClient, w io.Writer) error {
	if client == nil {
		return fmt.Errorf("no KMS client provided")
	}

	out, err := client.CreateKey(ctx, &kms.CreateKeyInput{
		Origin:   types.OriginTypeExternal,
		KeySpec:  types.KeySpecRsa2048,
		KeyUsage: types.KeyUsageTypeSignVerify,
	})
	if err != nil {
		return fmt.Errorf("create KMS key: %w", err)
	}
	if out == nil || out.KeyMetadata == nil || out.KeyMetadata.KeyId == nil || *out.KeyMetadata.KeyId == "" {
		return fmt.Errorf("create KMS key: missing key identifier in response")
	}

	if _, err := fmt.Fprintln(w, *out.KeyMetadata.KeyId); err != nil {
		return fmt.Errorf("write key identifier: %w", err)
	}
	return nil
}
